### ISSUE TITLE
Fehler

### ISSUE THREAD

**Issue by longo089** [VertexDezign/TargetFillLevel#3]
Hallo ich hab seit neustem einen Fehler.
Wenn ich im Drescher sitze und ihn entladen möchte stürzt sobald ich das rohr ausfahre das ganze Spiel ab. Ich habe jetzt lange experimentiert und habe festgestellt das wenn ich die Mod TargetFillLevel deaktiviere ich dieses Problem nicht mehr habe.

**Comment by schliesser** [comment]
Heyho @longo089 

Für eine Fehleranalyse brauche ich die log.txt.

> Bitte stelle sicher, dass du unseren Mod wie folgt getestet hast:
> 1. Entferne alle Mods aus deinem Mod-Ordner, außer dem/denjenigen, den/die du testen möchtest.
> 2. Teste immer auf der Standardkarte!
> 3. Lade die log.txt hoch. Nur diese Datei gibt Informationen über dein Spiel und die Fehler des Mods.

**Comment by schliesser** [comment]
Heyho @longo089 

kannst du mir Feedback geben, damit ich versuchen kann den Fehler zu reproduzieren?

* Was steht in der log.txt? -> Am besten die ganze Datei rein kopieren oder in ein [Gist](https://gist.github.com/) hochladen.
* Passiert das im Singleplayer oder Multiplayer?
* Standard Karte oder Mod Karte?
* Passiert das mit Basegame Fahrzeugen oder nur mit Mods?

**Comment by schliesser** [comment]
Closing due to lack of feedback. Also a new version is released.
